package envsetup

import (
	"fmt"
	"github.com/jfrog/jfrog-cli-core/v2/utils/coreutils"
	"time"
)

var frames = []string{
	"                      .dMMMMMN/                   \n                        -+oo/`                    \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n",
	"                       `/mMMy.                    \n                      .mMMMMMN+                   \n                      sMMMMMMMN`                  \n                      :NMMMMMMs                   \n                       .ohdhs:                    \n                          ``                      \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n                                                  \n                        `+mh-                     \n                       +mMMMNy.                   \n                      +MMMMMMMd`                  \n                      oMMMMMMMm`                  \n                      `smMMMNh-                   \n                        .:::-`                    \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                         `/-                      \n                       `+dMNy-                    \n                      -dMMMMMN+                   \n                      sMMMMMMMm`                  \n                    .`hMMMMMMMh:                  \n                    .+hoyNMMNdd-                  \n                      :sydddhy/                   \n                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                          :.                      \n                    .  `:hNNo.                    \n                `-``hhydNMMMMmo/-+-               \n                `-+yyshMMMMMMMNys+/               \n                   omdmMMMMMMMMmMm.               \n                   .-+ydmmmmmdhyso-               \n                        ``.``   `                 \n                                                  \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n                                                  \n                   `                              \n               `  -h/:/ossssh/...  ::             \n              `++//mNdhhdMMMdssydsso:             \n                .+mmo-`+mMMMNy:/shdy.             \n                  smMmdMMMMMMMMMMMMo`             \n                  :-sdNNMMMMMMNNNmhy-             \n                     `.-://///:::::.              \n                                                  \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n                                                  \n                                                  \n                                                  \n               ./           ..         `          \n         -s/   .sy/..-:////omy`      `os`         \n          `-/:::`dMNmmNNMMMMmmhyyh+:++:-          \n             .omssds:---:+s/...-/sys//+:          \n               :NNh/-.``.-/shhsooydmNd            \n              /oyNMMNmdmmNMMMMMMMMMMNms.`         \n              :-ommmNNNNMMMMMNNNNNmmmNdh+         \n                 ./oyhddmmmdmmddhddyyyyo`         \n                      `..-----..``.-.`            \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n                                                  \n                                                  \n      +o.    -+`            /+          `+:       \n      +dm:   `sy:          `y+         .hd:       \n       `-++-`/.`oh+::+oyyyydMm-``-.  `/+:-        \n          `:sNd-+MMNmmmmNMMNdhhhdNd+o+--sy.       \n            `:hmyhs:....-/+:::-.-/so++o:`         \n           `::-yMNy/-...-/sdNNmhyhdmMMy`          \n           ss`++omMMMNmNNMMMMMMMMMMMMN:ys```      \n           :: dmo/oydmNNNNNNNNNNNmdhs+yNm.oy      \n              `/yddyysssosooososssyhmmho/smo      \n                  .-/+osyyyyyyyso+////+oo/.       \n                                                  \n                                                  \n                                                  \n",
	"                                                  \n    -`      ``               .-                   \n   +Nd`     /s`              -/            `yh    \n    .+dy`    om/             oo           -yo.    \n      .+s/`./`.+h/.`.-://///yNN.   ``   `/s+.     \n        `:syys``NMmmmNNMMMMMMMMmyshmo.-+o+/o/     \n          `:hMd/hNmhs++oshmmy/-:/ohmmhs//s+`      \n            `+NNy/.       `.-:.   `-/shh.         \n         ./+. /mMms:.``..:odNMNhyhdmNMM+          \n        -mo ./ -dMMMNmmmNMMMMMMMMMMMMMd `s-       \n        .d. hm:``/hmNMMMMMMMMMMMMMNmdo.`+MN``y.   \n         `` :dNds/--:/+ossssssoo//:--+ymNm+`oMo   \n              -+ydmmdhhyyysssyyyhhdmNdyo/-odNy`   \n                   .-://+++++++//:-.-:/oyyo:`     \n                                                  \n                                                  \n",
	"  -`                                              \n +Nm`      .y.               /s              `sy  \n  `-.+/     `:/              .-             .`/-  \n    `oms` o- /hs`            yy           -dd.    \n      `/s+:` ``:do:--:+ossssdMN:   .`   `+s:`-:   \n        `:yddh.`NMNNNMMMMMMMMMMNdhdNs.-oo:ss`-/   \n          `:dMm/hMmhs+ooshmmy/-:/ohmmhs//o+:      \n         `. `oNNy/.       `.-:.   `-/shh:         \n       :oo.`  /mMms:.``..:odNMNhyhdmNMM+  ``      \n      sN+ .s`  -dMMMNmmmNMMMMMMMMMMMMMd   /h/  `  \n      sN  hNo.  `/hmNMMMMMMMMMMMMMNmdo. `-hMN` so`\n       :` :dNmy+-``.-:/+sssssso+/:-.`.:ohNMmo -mM:\n           `:odNNNdhyso++/:::/++osyhmNNNdy/.-sNMd`\n               `.:+osyhdmmmmmmmmhhyo+/:../sdNmy/  \n                                   `-/+oyo+:.     \n                                                  \n",
}

func PlayAnimation() {
	var esc = "\x1b"
	for i := 0; i < len(frames); i++ {
		if i > 0 {
			fmt.Printf(esc+"[%dA", 19)
		}
		coreutils.PrintMessage(frames[i])
		/////////////////maybe it'll be better to use tickers instead of sleep
		time.Sleep(125 * time.Millisecond)
	}

	time.Sleep(3 * time.Second)
	fmt.Printf(esc+"[%dA", 19)
	fmt.Printf(esc + "[0J")
}
